include: package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - test
    - "lib/firebase_options.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    file_names: false
    sort_pub_dependencies: false