name: ramadan
description: E-Ramadan App

publish_to: 'none' 


version: 1.0.0+1000

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State Management
  get: ^4.6.6

  #Firebase
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_analytics: ^9.3.8
  firebase_core_platform_interface: ^4.5.1

  #Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  #Network
  intl: ^0.19.0
  http: ^1.0.0

  #UI Operations
  lottie: ^1.4.1
  flutter_screenutil: ^5.9.0
  kartal: ^3.5.0
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  animated_text_kit: ^4.2.2
  intro_slider: ^4.2.1
  hexcolor: ^3.0.1

  #Other
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

dev_dependencies:
  


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/lottie/splash_slider_lottie/

