name: ramadan
description: E-Ramadan App

publish_to: 'none' 


version: 1.0.6+1060

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State Management
  get: ^4.6.6

  #Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.6
  firebase_remote_config: ^4.3.8
  firebase_performance: ^0.9.3+8

  #Maps
  permission_handler: ^11.0.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  #Network
  intl: ^0.19.0
  http: ^1.0.0

  #UI Operations
  lottie: ^2.7.0
  flutter_screenutil: ^5.9.0
  kartal: ^3.5.0
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  animated_text_kit: ^4.2.2
  intro_slider: ^4.2.1
  hexcolor: ^3.0.1
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.7

  #Other
  cupertino_icons: ^1.0.6
  google_fonts: 6.1.0
  flutter_local_notifications: ^16.3.2

  #Database
  shared_preferences: ^2.2.2

dev_dependencies:
  


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/lottie/splash_slider_lottie/
    - assets/lottie/splash/
    - assets/image/login/
    - assets/image/home/
    - assets/image/hadith/
    - assets/json/hadiths.json

